config/routes.rb
Myapp::Application.routes.draw do
  resources :document_registers
  resources :instrument_registrations
  resources :testings
  devise_for :users, :controllers => {registrations: "registrations"}
  get "home/index"
  get "home/minor"
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document_register.rb
class DocumentRegister < ApplicationRecord
  belongs_to :instrument_registrations
end

app/models/instrument_registration.rb
class InstrumentRegistration < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/document_registers_controller.rb
class DocumentRegistersController < ApplicationController
  before_action :set_document_register, only: [:show, :edit, :update, :destroy]

  # GET /document_registers
  # GET /document_registers.json
  def index
    @document_registers = DocumentRegister.all
  end

  # GET /document_registers/1
  # GET /document_registers/1.json
  def show
  end

  # GET /document_registers/new
  def new
    @document_register = DocumentRegister.new
  end

  # GET /document_registers/1/edit
  def edit
  end

  # POST /document_registers
  # POST /document_registers.json
  def create
    @document_register = DocumentRegister.new(document_register_params)

    respond_to do |format|
      if @document_register.save
        format.html { redirect_to @document_register, notice: 'Document register was successfully created.' }
        format.json { render :show, status: :created, location: @document_register }
      else
        format.html { render :new }
        format.json { render json: @document_register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_registers/1
  # PATCH/PUT /document_registers/1.json
  def update
    respond_to do |format|
      if @document_register.update(document_register_params)
        format.html { redirect_to @document_register, notice: 'Document register was successfully updated.' }
        format.json { render :show, status: :ok, location: @document_register }
      else
        format.html { render :edit }
        format.json { render json: @document_register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_registers/1
  # DELETE /document_registers/1.json
  def destroy
    @document_register.destroy
    respond_to do |format|
      format.html { redirect_to document_registers_url, notice: 'Document register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_register
      @document_register = DocumentRegister.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_register_params
      params.require(:document_register).permit(:name, :instrument_registrations_id, :document_file)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @mainTitle = "Instituto de Desenvolvimento Econômico e Social - INDES"
    @mainDesc = "Gerenciamento de documentos"
  end

  def minor
  end
end

app/controllers/instrument_registrations_controller.rb
class InstrumentRegistrationsController < ApplicationController
  before_action :set_instrument_registration, only: [:show, :edit, :update, :destroy]

  # GET /instrument_registrations
  # GET /instrument_registrations.json
  def index
    @instrument_registrations = InstrumentRegistration.all
  end

  # GET /instrument_registrations/1
  # GET /instrument_registrations/1.json
  def show
  end

  # GET /instrument_registrations/new
  def new
    @instrument_registration = InstrumentRegistration.new
  end

  # GET /instrument_registrations/1/edit
  def edit
  end

  # POST /instrument_registrations
  # POST /instrument_registrations.json
  def create
    @instrument_registration = InstrumentRegistration.new(instrument_registration_params)

    respond_to do |format|
      if @instrument_registration.save
        format.html { redirect_to @instrument_registration, notice: 'Instrument registration was successfully created.' }
        format.json { render :show, status: :created, location: @instrument_registration }
      else
        format.html { render :new }
        format.json { render json: @instrument_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instrument_registrations/1
  # PATCH/PUT /instrument_registrations/1.json
  def update
    respond_to do |format|
      if @instrument_registration.update(instrument_registration_params)
        format.html { redirect_to @instrument_registration, notice: 'Instrument registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument_registration }
      else
        format.html { render :edit }
        format.json { render json: @instrument_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instrument_registrations/1
  # DELETE /instrument_registrations/1.json
  def destroy
    @instrument_registration.destroy
    respond_to do |format|
      format.html { redirect_to instrument_registrations_url, notice: 'Instrument registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument_registration
      @instrument_registration = InstrumentRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_registration_params
      params.require(:instrument_registration).permit(:instrument_number, :internal_number, :extra_number, :object_agreement, :granting_organ, :linked_organ, :existence_im, :instituition_name, :value_transfer, :counterpart_value, :total, :signature_date, :end_date, :suspensive_date, :type, :address, :open_date, :organ, :user, :signature, :instrument_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name, class_name = nil)
        if params[:controller] == controller_name
         class_name == nil ? "active" : class_name
        else
           nil
        end
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/document_registers_helper.rb
module DocumentRegistersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instrument_registrations_helper.rb
module InstrumentRegistrationsHelper
    def instrument_tp
        [
          'Selecione', 'Obra', 'Serviço', 'Bens', 'Sem tipo'
        ]
      end

      def existence_im
        [
          'Selecione', 'Sim', 'Não'
        ]
      end
end

app/views/document_registers/_form.html.erb
<%= form_with(model: document_register, local: true, class: 'form-horizontal') do |form| %>
      <div class="form-group <%= document_register.errors[:name].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Nome do Documento:</label>
      <div class="col-sm-10">
        <%= form.text_field :name, class: 'form-control' %>
        <% if document_register.errors[:name].any? %>
          <span class="help-block m-b-none font-bold"><%= document_register.errors[:name].first %></span>
        <% end %>
      </div>
    </div>    
      <div class="form-group <%= document_register.errors[:instrument_registrations_id].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Instumento vinculado:</label>
      <div class="col-sm-10">
        <%= form.text_field :instrument_registrations_id, class: 'form-control' %>
        <% if document_register.errors[:instrument_registrations_id].any? %>
          <span class="help-block m-b-none font-bold"><%= document_register.errors[:instrument_registrations_id].first %></span>
        <% end %>
      </div>
    </div>    
      <div class="form-group <%= document_register.errors[:document_file].any? ? 'has-error' : '' %>">
      <label class="col-sm-2 control-label">Documento a ser anexado:</label>
      <div class="col-sm-10">
        <div class="file-upload">
          <label for="file-input">
            <span class=""><a style="color:#0000000;" class="btn btn-primary">Selecionar arquivo...</a></span>            
        </label>
          <%= form.file_field :document_file, id:"file-input" %>         
          
        <% if document_register.errors[:document_file].any? %>
          <span class="help-block m-b-none font-bold"><%= document_register.errors[:document_file].first %></span>
        <% end %>
      </div>
    </div>
    <br>    
    <br>
    <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
        <%= link_to 'Cancelar', document_registers_path, :class => 'btn btn-white' %>     
        <%= form.submit 'Salvar', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/document_registers/_header.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Cadastro de Documento</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for :controller => 'home', :action => 'index' %>">Home</a>
      </li>      
      <li class="active">
        <strong>Cadastro de Documento</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">
  </div>
</div>

app/views/document_registers/edit.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">          
          <h5>&nbsp;Editando document_register</h5>
        </div>
        <div class="ibox-content">
            <%= render 'form', document_register: @document_register %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/document_registers/index.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Novo Documento</h5>
          <div class="ibox-tools">
            <a class="collapse-link">
            </a>
          </div>
        </div>
        <div class="ibox-content-scaffold">
          <table class="table table-striped table-hover table-results">
            <thead>
              <tr>
                <th>Nome do Documento</th>
                <th>Insrumento Vinculado</th>
                <th>Documento Anexado</th>                                
                <th class="col-sm-3">Ações</th>
              </tr>
            </thead>            
            <tbody>
              <% @document_registers.each do |document_register| %>
                <tr>
                  <td><%= document_register.name %></td>
                  <td><%= document_register.instrument_registrations %></td>
                  <td><%= document_register.document_file %></td>
                  <td>
                    <%= link_to fa_icon('eye'),  document_register, class: 'btn btn-sm btn-success' %>                    
                    <%= link_to fa_icon('edit'), edit_document_register_path(document_register), class: 'btn btn-sm btn-warning' %>
                    <%= link_to fa_icon('trash'), document_register, method: :delete, data: { confirm: I18n.t('app.messages.are_you_sure') }, class: 'btn btn-sm btn-danger' %>                    
                  </td>                    
                </tr>
              <% end %>
            </tbody>            
            <tfoot>
              <tr>
                <td>                  
                  <%= link_to fa_icon('plus'), new_document_register_path, class: 'btn btn-md btn-primary' %></td>                  
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
        $('.table-results').DataTable({
            pageLength: 10,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'PCE'},
                {extend: 'pdf', title: 'PCE'},
    
                {extend: 'print',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');
    
                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ],
            language: {
              "sEmptyTable": "Nenhum registro encontrado",
              "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
              "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
              "sInfoFiltered": "(Filtrados de _MAX_ registros)",
              "sInfoPostFix": "",
              "sInfoThousands": ".",
              "sLengthMenu": "_MENU_ resultados por página",
              "sLoadingRecords": "Carregando...",
              "sProcessing": "Processando...",
              "sZeroRecords": "Nenhum registro encontrado",
              "sSearch": "Pesquisar",
              "oPaginate": {
                  "sNext": "Próximo",
                  "sPrevious": "Anterior",
                  "sFirst": "Primeiro",
                  "sLast": "Último"
              },
              "oAria":{
                  "sSortAscending": ": Ordenar colunas de forma ascendente",
                  "sSortDescending": ": Ordenar colunas de forma descendente"
              },
              "buttons": {
                "copy": "Copiar",
                "print": "Imprimir"
                              }
            }
        });
    });
  </script>
<% end %>

app/views/document_registers/new.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Novo Documento</h5>
        </div>
        <div class="ibox-content-scaffold">
            <%= render 'form', document_register: @document_register %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/document_registers/show.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Mostrando document_register</h5>
        </div>
        <div class="ibox-content">
            <form class="form-horizontal">
                              <div class="form-group"><label class="col-sm-2 control-label">Nome do Documento:</label>
                  <div class="col-sm-10">
                    <p class="form-control-static">
                      <%= @document_register.name %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label class="col-sm-2 control-label">Insrumento Vinculado:</label>
                  <div class="col-sm-10">
                    <p class="form-control-static">
                      <%= @document_register.instrument_registrations %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label class="col-sm-2 control-label">Documento Anexado:</label>
                  <div class="col-sm-10">
                    <p class="form-control-static">
                      <%= @document_register.document_file %>
                    </p>
                  </div>                  
                </div>
                            <div class="hr-line-dashed">
              </div>                    
              <div class="form-group">
                  <div class="col-sm-4">
                      <%= link_to 'Voltar', document_registers_path, :class => 'btn btn-white' %>            
                      <%= link_to 'Editar', edit_document_register_path(@document_register), :class => "btn btn-primary" %>               
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/home/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    <%= @mainTitle %>
                </h1>
                <small>
                    <%= @mainDesc %>
                </small>
            </div>
        </div>
    </div>
</div>

app/views/home/minor.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="text-center m-t-lg">
                <h1>
                    Simple example of second view
                </h1>
                <small>Configure in home_controller.rb as minor view.</small>
            </div>
        </div>
    </div>
</div>

app/views/instrument_registrations/index.html.erb
<%= render 'header' %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Novo Instrumento</h5>
          <div class="ibox-tools">
            <a class="collapse-link">
            </a>
          </div>
        </div>
        <div class="ibox-content-scaffold">
          <table class="table table-striped table-hover table-results">
            <thead>
              <tr>
                <th>Número do Instrumento</th>
                <th>Número Interno</th>
                <th>Número Extra</th>
                <th>Objeto do Convênio</th>
                <th>Orgão Concendente</th>
                <th>Orgão Vinculado </th>                                 
                <th class="col-sm-3">Ações</th>
              </tr>
            </thead>            
            <tbody>
              <% @instrument_registrations.each do |instrument_registration| %>
                <tr>
                  <td><%= instrument_registration.instrument_number %></td>
                  <td><%= instrument_registration.internal_number %></td>
                  <td><%= instrument_registration.extra_number %></td>
                  <td><%= instrument_registration.object_agreement %></td>
                  <td><%= instrument_registration.granting_organ %></td>
                  <td><%= instrument_registration.linked_organ %></td>
                  <td>
                    <%= link_to fa_icon('eye'),  instrument_registration, class: 'btn btn-sm btn-success' %>                    
                    <%= link_to fa_icon('edit'), edit_instrument_registration_path(instrument_registration), class: 'btn btn-sm btn-warning' %>
                    <%= link_to fa_icon('trash'), instrument_registration, method: :delete, data: { confirm: I18n.t('app.messages.are_you_sure') }, class: 'btn btn-sm btn-danger' %>                    
                  </td>                    
                </tr>
              <% end %>
            </tbody>            
            <tfoot>
              <tr>
                <td>                  

                  <%= link_to fa_icon('plus'), new_instrument_registration_path, class: 'btn btn-md btn-primary' %></td>                  
                  
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
        $('.table-results').DataTable({
            pageLength: 10,
            responsive: true,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                { extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'PCE'},
                {extend: 'pdf', title: 'PCE'},
    
                {extend: 'print',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');
    
                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ],
            language: {
              "sEmptyTable": "Nenhum registro encontrado",
              "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
              "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
              "sInfoFiltered": "(Filtrados de _MAX_ registros)",
              "sInfoPostFix": "",
              "sInfoThousands": ".",
              "sLengthMenu": "_MENU_ resultados por página",
              "sLoadingRecords": "Carregando...",
              "sProcessing": "Processando...",
              "sZeroRecords": "Nenhum registro encontrado",
              "sSearch": "Pesquisar",
              "oPaginate": {
                  "sNext": "Próximo",
                  "sPrevious": "Anterior",
                  "sFirst": "Primeiro",
                  "sLast": "Último"
              },
              "oAria":{
                  "sSortAscending": ": Ordenar colunas de forma ascendente",
                  "sSortDescending": ": Ordenar colunas de forma descendente"
              },
              "buttons": {
                "copy": "Copiar",
                "print": "Imprimir"
                              }
            }
        });
    });
  </script>
<% end %>

app/views/instrument_registrations/show.html.erb
<%= render 'header' %>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-content-scaffold">
        <center style="color:#49667d;"><h1> Instrumento <%= @instrument_registration.instrument_number %></h1></center>        
        <div class="hr-line-dashed"></div>
            <h3 style="color:#49667d;">I. Dados Gerais </h3>
            <br>
            <form class="form-horizontal">
                <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Número Interno:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.internal_number %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Número Extra:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.extra_number %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Objeto do Convênio:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.object_agreement %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Orgão Concendente:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.granting_organ %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Orgão Vinculado:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.linked_organ %>
                    </p>
                  </div>                  
                </div>
                <br>
                <h3 style="color:#49667d;"> II. Instituição Mandátaria - IM </h3>
                <br>
                 <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Há Existência de IM?</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.existence_im %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Nome da Instituição:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.instituition_name %>
                    </p>
                  </div>                  
                </div>
                <br>
                <h3 style="color:#49667d;"> III. Valores </h3>
                <br>
                             <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Valor do Repasse:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.value_transfer %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Valor da Contrapartida:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.counterpart_value %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Total:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.total %>
                    </p>
                  </div>                  
                </div>
                <br>
                  <h3 style="color:#49667d;">IV. Prazos</h3>    
                <br>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Data de Assinatura:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.signature_date %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Data do Término de Vigência:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.end_date %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Data da Suspensiva:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.suspensive_date %>
                    </p>
                  </div>                  
                </div>
                <br>
                  <h3 style="color:#49667d;">V. Especificações </h3>    
                <br>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Tipo:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.instrument_type %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Endereço:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.address %>
                    </p>
                  </div>                  
                </div>
                <br>
                  <h3 style="color:#49667d;"> VI. Dados da Inserção </h3>    
                <br>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Data de Abertura:</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.open_date %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Orgão (Prefeitura):</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.organ %>
                    </p>
                  </div>                  
                </div>
                              <div class="form-group"><label style="color:#49667d;" class="col-sm-2 control-label">Perfil (Nome do Usuário):</label>
                  <div class="col-sm-10">
                    <p style="color:#565555;" class="form-control">
                      <%= @instrument_registration.user %>
                    </p>
                  </div>                  
                </div>
                <div class="hr-line-dashed">
                 <center style="color:#49667d;"><h1> Assinado por: <%= @instrument_registration.signature  %></h1></center>        
              </div>                           
              <br>
              <br>
                <div class="form-group">
                  <div class="col-sm-4">
                      <%= link_to 'Voltar', instrument_registrations_path, :class => 'btn btn-white' %>            
                      <%= link_to 'Editar', edit_instrument_registration_path(@instrument_registration), :class => "btn btn-primary" %>               
                  </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>  